version: '2'
services:
  ship:
    build: .
    ports:
      - '3000:3000'
    environment:
      HIDDEN_SERVICES: 'ship_ship,traefik_traefik,portainer_agent,portainer_portainer,traefik_socket-proxy'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
